spring.datasource.url=jdbc:h2:mem:clasesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
server.port=8082
spring.application.name=microservicio-clases

# dirección del servicio de entrenadores (puede cambiar en despliegue)
entrenador.service.url=http://localhost:8083/api/entrenadores

# dirección del servicio de equipos (puede cambiar en despliegue)
equipo.service.url=http://localhost:8084/api/equipos

# dirección del servicio de miembros (puede cambiar en despliegue)
miembro.service.url=http://localhost:8081/api/miembros

# Keycloak JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/gimnasio
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

# Keycloak (cliente confidential)
keycloak.auth-server-url=http://localhost:8180
keycloak.realm=gimnasio
keycloak.resource=gym-backend
keycloak.public-client=false
keycloak.credentials.secret=g7nM2pQ5rT8vX1yB4cF0hJ3kL6nP9sU

logging.level.org.springframework.security=DEBUG

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=monitoreo-grupo
spring.kafka.consumer.auto-offset-reset=earliest

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
