server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/gimnasio
  cloud:
    gateway:
      routes:
        - id: resumen-miembro
          uri: no://op
          predicates:
            - Path=/resumen/miembros/{miembroId}
          filters:
            - name: MemberSummaryAggregation
        - id: miembros
          uri: lb://microservicio-miembros
          predicates:
            - Path=/miembros,/miembros/**
          filters:
            - RewritePath=/miembros(?<segment>/?.*), /api/miembros${segment}
        - id: clases
          uri: lb://microservicio-clases
          predicates:
            - Path=/clases,/clases/**
          filters:
            - RewritePath=/clases(?<segment>/?.*), /api/clases${segment}
        - id: entrenadores
          uri: lb://microservicio-entrenadores
          predicates:
            - Path=/entrenadores,/entrenadores/**
          filters:
            - RewritePath=/entrenadores(?<segment>/?.*), /api/entrenadores${segment}
        - id: equipos
          uri: lb://microservicio-equipos
          predicates:
            - Path=/equipos,/equipos/**
          filters:
            - RewritePath=/equipos(?<segment>/?.*), /api/equipos${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
