server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/gimnasio
  cloud:
    gateway:
      routes:
        - id: miembros
          uri: http://localhost:8081
          predicates:
            - Path=/miembros/**
          filters:
            - StripPrefix=1
        - id: clases
          uri: http://localhost:8082
          predicates:
            - Path=/clases/**
          filters:
            - StripPrefix=1
        - id: entrenadores
          uri: http://localhost:8083
          predicates:
            - Path=/entrenadores/**
          filters:
            - StripPrefix=1
        - id: equipos
          uri: http://localhost:8084
          predicates:
            - Path=/equipos/**
          filters:
            - StripPrefix=1
