
spring.application.name=microservicio-pagos
server.port=8085

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Message converter settings (use JSON for messages)
spring.jackson.serialization.write-dates-as-timestamps=false

# Listener defaults
spring.rabbitmq.listener.simple.acknowledge-mode=auto

# Keycloak JWT (same realm used by other microservicios)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/gimnasio
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

