spring.datasource.url=jdbc:h2:mem:entrenadoresdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
server.port=8083
spring.application.name=microservicio-entrenadores

# Keycloak JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/gimnasio
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

# Keycloak (cliente confidential)
keycloak.auth-server-url=http://localhost:8180
keycloak.realm=gimnasio
keycloak.resource=gym-backend
keycloak.public-client=false
keycloak.credentials.secret=g7nM2pQ5rT8vX1yB4cF0hJ3kL6nP9sU

logging.level.org.springframework.security=DEBUG

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest